name: C++

on:
  push:
    branches: [main]
  pull_request:

env:
  CABIN_TERM_COLOR: always
  CXX: g++-14  # default compiler to build
  LLVM_VER: 21

permissions:
  contents: read

jobs:
  apple-clang:
    name: "build & test (macOS ${{ matrix.osver }} - Apple Clang - ${{ matrix.build }})"
    runs-on: macos-${{ matrix.osver }}
    strategy:
      fail-fast: false
      matrix:
        osver: [15, 26]
        build: [dev, release]
    env:
      CXX: c++
    steps:
      - uses: actions/checkout@v5

      - name: Setup macOS dependencies
        uses: ./.github/actions/setup-macos-deps

      - name: Build & Test
        uses: ./.github/actions/build-and-test
        with:
          build: ${{ matrix.build }}
          coverage: false

  clang:
    name: "build & test (Linux - Clang ${{ matrix.ver }} - ${{ matrix.build }})"
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        build: [dev, release]
        ver: [19, 20, 21]
    env:
      CXX: clang++-${{ matrix.ver }}
    steps:
      - uses: actions/checkout@v5

      - name: Setup Ubuntu dependencies
        uses: ./.github/actions/setup-ubuntu-deps

      - name: Setup Clang ${{ matrix.ver }}
        uses: ./.github/actions/setup-llvm
        with:
          version: ${{ matrix.ver }}

      - name: Build & Test
        uses: ./.github/actions/build-and-test
        with:
          build: ${{ matrix.build }}
          coverage: false

  gcc:
    name: "build & test (Linux - GCC ${{ matrix.ver }} - ${{ matrix.build }}${{ matrix.coverage && ' - coverage' || '' }})"
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        build: [dev, release]
        ver: [14, 15]
        coverage: [false]
        include:
          # Coverage testing with GCC 14
          - build: dev
            ver: 14
            coverage: true
    env:
      CXX: g++-${{ matrix.ver }}
    steps:
      - uses: actions/checkout@v5

      - name: Setup Ubuntu dependencies
        uses: ./.github/actions/setup-ubuntu-deps

      - name: Setup GCC
        if: matrix.ver == 15
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install gcc@15 binutils
          echo "$(brew --prefix binutils)/bin" >> "$GITHUB_PATH"
          echo "CXX=$(brew --prefix gcc@15)/bin/g++-15" >> "$GITHUB_ENV"

      - name: Install lcov
        if: matrix.coverage
        run: sudo apt-get install -y lcov

      - name: Build & Test
        uses: ./.github/actions/build-and-test
        with:
          build: ${{ matrix.build }}
          coverage: ${{ matrix.coverage }}

      - name: Print coverage
        if: success() && matrix.coverage
        run: |
          lcov --capture --directory . --no-external \
               --gcov-tool "gcov-${{ matrix.ver }}"  \
               --output-file coverage.info
          lcov --list coverage.info

  package-test:
    needs: [apple-clang, clang, gcc]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - name: Setup Ubuntu dependencies
        uses: ./.github/actions/setup-ubuntu-deps

      - name: Build cabin
        run: make BUILD=release -j4

      - name: Install nFPM
        run: |
          echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
          sudo apt-get update
          sudo apt-get install -y nfpm

      - name: Test DEB package creation
        run: nfpm pkg --packager deb
        env:
          CABIN_VERSION: 0.0.0+${{ github.sha }}

      - name: Test RPM package creation
        run: nfpm pkg --packager rpm
        env:
          CABIN_VERSION: 0.0.0+${{ github.sha }}

      - name: List created packages
        run: ls -la ./*.deb ./*.rpm

      - name: Verify package contents
        run: |
          dpkg-deb --contents ./*.deb | grep '/usr/bin/cabin'
          rpm -qlp ./*.rpm | grep '/usr/bin/cabin'

      - name: Test DEB package installation
        run: sudo dpkg -i ./*.deb

      - name: Create test project
        run: cabin new test_pj
        working-directory: ${{ runner.temp }}

      - name: Test cabin functionality
        run: cabin run | grep 'Hello, world!'
        working-directory: ${{ runner.temp }}/test_pj

  format:
    needs: [apple-clang, clang, gcc]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - name: Setup dependencies
        uses: ./.github/actions/setup-ubuntu-deps

      - name: Build Cabin
        run: make BUILD=release -j4

      - name: Install clang-format-${{ env.LLVM_VER }}
        uses: ./.github/actions/setup-llvm
        with:
          version: ${{ env.LLVM_VER }}

      - name: cabin fmt
        run: ./build/cabin fmt --check -vv
        env:
          CABIN_FMT: clang-format-${{ env.LLVM_VER }}

  lint:
    needs: [apple-clang, clang, gcc]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - name: Setup dependencies
        uses: ./.github/actions/setup-ubuntu-deps

      - name: Build Cabin
        run: make BUILD=release -j4

      - uses: actions/setup-python@v6
        with:
          python-version: '3.*'

      - name: Install cpplint
        run: pip install cpplint

      - name: Show cpplint version
        run: cpplint --version

      - name: cabin lint
        run: ./build/cabin lint -vv

  clang-tidy:
    needs: [apple-clang, clang, gcc]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - name: Setup dependencies
        uses: ./.github/actions/setup-ubuntu-deps

      - name: Build Cabin
        run: make BUILD=release -j4

      - name: Install clang-tidy-${{ env.LLVM_VER }}
        uses: ./.github/actions/setup-llvm
        with:
          version: ${{ env.LLVM_VER }}

      - name: cabin tidy
        run: ./build/cabin tidy -vv
        env:
          CABIN_TIDY: run-clang-tidy-${{ env.LLVM_VER }}
